apiVersion: batch/v1
kind: CronJob
metadata:
  name: m3uparser-job
  namespace: jellyfin
spec:
  schedule: "0 */12 * * *"  # Every 12 hours
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: m3uparser
        spec:
          restartPolicy: Never
          containers:
            - name: m3uparser
              image: danifuu/m3uparser:latest
              envFrom:
                - secretRef:
                    name: jellyfin-secret
              volumeMounts:
              - mountPath: /usr/src/app/VODS
                name: media
              - mountPath: /usr/src/app/logs/
                name: media
          volumes:
            - name: media
              persistentVolumeClaim:
                claimName: jellyfin-media
