extraContainers:
  - name: m3uparser
    image: danifuu/m3uparser:latest
    envFrom:
      - secretRef:
          name: jellyfin-secret
    volumeMounts:
    - mountPath: /usr/src/app/VODS
      name: media
    - mountPath: /usr/src/app/logs/
      name: media

persistence:
  config:
    size: 20Gi # Increased size to store logs/metadata

# finally! adding gpu support for hardware acceleration of transcoding tasks
resources:
  limits:
    gpu.intel.com/i915: 1
