apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Infrastructure
  - infrastructure/cert-manager
  - infrastructure/envoy-gateway
  - infrastructure/external-dns
  - infrastructure/intel-device-plugin
  - infrastructure/longhorn
  - infrastructure/metallb
  - infrastructure/metrics-server
  - infrastructure/monitoring
  - infrastructure/node-feature-discovering

  # Services
  # - services/jellyfin  # Temporarily disabled
  - services/telegram-bot
