apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: node-feature-discovery
  namespace: nfd-system
spec:
  interval: 12h
  url: oci://registry.k8s.io/nfd/charts/node-feature-discovery
  ref:
    tag: "0.18.3"
