apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  namespace: telegram-bot
  labels:
    app: telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
        - name: bot
          image: danifuu/telegram-bot:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: telegram-bot-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
