apiVersion: v1
kind: Service
metadata:
  name: telegram-bot
  namespace: telegram-bot
  labels:
    app: telegram-bot
spec:
  selector:
    app: telegram-bot
  ports:
    - name: http
      port: 80
      targetPort: http
