apiVersion: v1
kind: Secret
metadata:
  name: project-zomboid-config
  namespace: project-zomboid
type: Opaque
stringData:
  ADMIN_PASSWORD: "AdminPleaseChangeMe"
  ADMIN_USERNAME: "admin"
  AUTOSAVE_INTERVAL: "15"
  BACKUPS_COUNT: "5"
  BACKUPS_PERIOD: "120"
  DIRECT_PORT: "16262"
  GAME_PORT: "16261"
  MAP_NAMES: "Muldraugh, KY"
  MAX_MEMORY: "10g"
  MAX_PLAYERS: "16"
  MOD_IDS: ""
  MOD_NAMES: ""
  PAUSE_EMPTY: "true"
  PING_LIMIT: "400"
  PVP: "true"
  PUBLIC: "true"
  RCON_PASSWORD: "RCONPleaseChangeMe"
  RCON_PORT: "27015"
  SERVER_IP: ""
  SERVER_NAME: "Zomboid Containerized"
  SERVER_PASSWORD: ""
  STEAM_VAC: "true"
  ANTI_CHEAT_TYPE21: "true"
  BETA_BRANCH: ""
