image:
  repository: sknnr/zomboid-dedicated-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  externalIPs: []
  annotations: {}

resources:
  requests:
    memory: 3G
    cpu: 500m

volumes:
  serverPVC:
    size: 50Gi
  dataPVC:
    size: 50Gi
  storageClassName: "longhorn"
