image:
  repository: sknnr/zomboid-dedicated-server
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  externalIPs: []
  annotations: {}

resources:
  requests:
    memory: 12G
    cpu: 6.0

volumes:
  serverPVC:
    size: 50Gi
  dataPVC:
    size: 50Gi
  storageClassName: "longhorn"
