apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - podmonitor.yaml
configMapGenerator:
  - name: flux-grafana-dashboards
    files:
      - dashboards/flux/control-plane.json
      - dashboards/flux/cluster.json
      - dashboards/flux/logs.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled
      annotations:
        grafana_folder: Flux
  - name: grafana-dashboards
    files:
      - dashboards/cluster-logs.json
      - dashboards/nodes.json
    options:
      labels:
        grafana_dashboard: "1"
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: jellyfin-grafana-dashboard
    files:
      - dashboards/jellyfin.json
    options:
      labels:
        grafana_dashboard: "1"
        kustomize.toolkit.fluxcd.io/substitute: disabled
      annotations:
        grafana_folder: Jellyfin
